### ISSUE TITLE
 python application based project:Youtube Video downloader

### ISSUE THREAD

**Issue by aniketartani** [aniketartani/Pyhton-Basic-Projects#15]

**Comment by Shahzeb-A** [comment]
Hello @aniketartani  could you please explain more details about the project?

**Comment by aniketartani** [comment]
choose any python project and let me know.I will assign

**Comment by Shahzeb-A** [comment]
A youtube Downloader made by python?

**Comment by aniketartani** [comment]
Ya go ahead, i will assign you soon.

**Comment by Shahzeb-A** [comment]
I can do text to speech. 
Can you assign me to it?

**Comment by aniketartani** [comment]
Text to speech is already done, you can check in repo.

**Comment by aniketartani** [comment]
ok

**Comment by aniketartani** [comment]
choose any other

**Comment by Shahzeb-A** [comment]
I can do a Video to Audio converter.
Can you assign me to it?

**Comment by aniketartani** [comment]
The project's those are in readme file are already uploaded. Please choose
another from your choice.

**Comment by Shahzeb-A** [comment]
I can do Youtube Video downloader using python.
Can you assign me to it?

**Comment by aniketartani** [comment]
sure do it and please add in the readme file too.Assigning you

**Comment by aniketartani** [comment]
are you interested in teaching? Would you like to become an instructor at upstartleague.tech

**Comment by Shahzeb-A** [comment]
Sure why not?
I would love this oppurtunity

**Comment by aniketartani** [comment]
dm, your mob no.

**Comment by aniketartani** [comment]
send your details like WhatsApp no, resume(if you have) at founder@upstartleague.tech mail id

**Comment by aniketartani** [comment]
give me your WhatsApp no here.I'll text you there

**Comment by Shahzeb-A** [comment]
+966551028874
I'll wait for ur message

**Comment by Shahzeb-A** [comment]
@aniketartani I have finished the project kindly check your pull requests
